### ISSUE TITLE
[BUG] Src doesn't compile

### ISSUE THREAD

**Issue by YeahOMA** [IUDevman/gamesense-client#191]
I cloned the repository, ran gradlew setupDecompWorkspace, and then ran gradlew runClient. It crashed after a few seconds with this error message.

```
java.lang.NullPointerException: Rendering screen
        at net.minecraft.client.gui.FontRenderer.redirect$drawCustomFontStringWithShadow$zzh000(FontRenderer.java:1088)
        at net.minecraft.client.gui.FontRenderer.drawStringWithShadow(FontRenderer.java:311)
        at net.minecraft.client.gui.Gui.drawString(Gui.java:135)
        at net.minecraftforge.client.ForgeHooksClient.renderMainMenu(ForgeHooksClient.java:357)
        at net.minecraft.client.gui.GuiMainMenu.drawScreen(GuiMainMenu.java:576)
        at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
        at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1177)
        at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1208)
        at net.minecraft.client.Minecraft.run(Minecraft.java:441)
        at net.minecraft.client.main.Main.main(Main.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
        at GradleStart.main(GradleStart.java:25)
```

```
Stacktrace:
        at net.minecraft.client.gui.FontRenderer.redirect$drawCustomFontStringWithShadow$zzh000(FontRenderer.java:1088)
        at net.minecraft.client.gui.FontRenderer.drawStringWithShadow(FontRenderer.java:311)
        at net.minecraft.client.gui.Gui.drawString(Gui.java:135)
        at net.minecraftforge.client.ForgeHooksClient.renderMainMenu(ForgeHooksClient.java:357)
        at net.minecraft.client.gui.GuiMainMenu.drawScreen(GuiMainMenu.java:576)
        at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)

-- Screen render details --
Details:
        Screen name: net.minecraft.client.gui.GuiMainMenu
        Mouse location: Scaled: (119, 53). Absolute: (238, 373)
        Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
        at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1177)
        at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1208)
        at net.minecraft.client.Minecraft.run(Minecraft.java:441)
        at net.minecraft.client.main.Main.main(Main.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
        at GradleStart.main(GradleStart.java:25)
```

**Comment by IUDevman** [comment]
Do setupdecompworkspace,
